# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-26 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alias'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名字')),
                ('textbook', models.CharField(max_length=20, verbose_name='出处')),
                ('note', models.TextField(verbose_name='备注')),
            ],
            options={
                'verbose_name_plural': 'alias',
            },
        ),
    ]
