# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-26 15:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20170126_2322'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Persons',
            new_name='Names',
        ),
        migrations.AlterModelOptions(
            name='names',
            options={},
        ),
    ]
