# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-31 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20170126_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='names',
            name='alias',
            field=models.CharField(max_length=20, null=True, verbose_name='别名'),
        ),
        migrations.AlterField(
            model_name='names',
            name='name',
            field=models.CharField(max_length=10, verbose_name='名字'),
        ),
        migrations.AlterField(
            model_name='names',
            name='textbook',
            field=models.CharField(max_length=50, verbose_name='出处'),
        ),
    ]
