# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-02 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ksitiscry', '0002_auto_20170122_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avalokiscry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signtype', models.CharField(max_length=4, verbose_name='上中下签')),
                ('signmetaphor', models.CharField(max_length=12, verbose_name='签喻')),
                ('signpoem', models.CharField(max_length=64, verbose_name='签诗')),
                ('signotes', models.TextField(verbose_name='签释')),
            ],
        ),
    ]
