# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-19 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_mining', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='results',
            old_name='solution',
            new_name='summary',
        ),
        migrations.AddField(
            model_name='words',
            name='fromtext',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='results',
            name='item',
            field=models.CharField(max_length=20),
        ),
    ]
