# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-19 13:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('text_mining', '0002_auto_20170119_1549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='words',
            old_name='fromtext',
            new_name='isfrom',
        ),
    ]
