# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-26 15:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('text_mining', '0005_auto_20170126_2333'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Persons',
            new_name='Inames',
        ),
        migrations.AlterModelOptions(
            name='inames',
            options={'verbose_name_plural': 'inames'},
        ),
    ]
