# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-26 15:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('text_mining', '0006_auto_20170126_2337'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inames',
        ),
    ]
