# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-31 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_mining', '0008_auto_20170131_1406'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phrases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='词组')),
                ('degrees', models.IntegerField(verbose_name='词频')),
                ('textbook', models.CharField(max_length=50, verbose_name='词频')),
            ],
        ),
        migrations.AlterField(
            model_name='results',
            name='summary',
            field=models.TextField(verbose_name='结果'),
        ),
        migrations.AlterField(
            model_name='results',
            name='textbook',
            field=models.CharField(max_length=50, verbose_name='文本'),
        ),
        migrations.AlterField(
            model_name='words',
            name='degrees',
            field=models.IntegerField(verbose_name='字频'),
        ),
        migrations.AlterField(
            model_name='words',
            name='name',
            field=models.CharField(max_length=2, verbose_name='字'),
        ),
        migrations.AlterField(
            model_name='words',
            name='textbook',
            field=models.CharField(max_length=50, verbose_name='文本'),
        ),
    ]
