# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-31 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_mining', '0009_auto_20170131_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='names',
            name='degrees',
            field=models.IntegerField(null=True, verbose_name='出现频率'),
        ),
    ]
