# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-18 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='example',
            name='item',
            field=models.CharField(max_length=48),
        ),
    ]
